server:
  port: 8083
spring:
  application:
    name: tarea
  jackson:
    date-format: dd/MM/yyyy HH:mm:ss
    serialization.WRITE_DATES_AS_TIMESTAMPS: false
  datasource:
    username: sa
    password: sa
    url: jdbc:sqlserver://COMANDOPC;databaseName=coopeuch
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    platform: mssql
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:
      ddl-auto: none
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    h2:
      console:
        enabled: true
        path: /h2-console

### Chassis Configs ###


# Metrics starter properties
metrics:
  enabled: false

# Logging starter properties
logging:
  level:
    root: INFO
  format: JSON
  debug: false

# Response wrapping settings
web:
  advice:
    response:
      formatting:
        enabled: false





